version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cno
    volumes:
      - db-data:/var/lib/postgresql/data
      - shared-data:/shared
    ports:
      - "5432:5432"
    networks:
      - stream-network

  app:
    build: .
    volumes:
      - ./dags:/home
      - shared-data:/shared
    tty: true
    networks:
      - stream-network
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/cno

volumes:
  db-data:
  shared-data:

networks:
  stream-network:
