#Runs ondemand container
# command: docker-compose up --build -d
# OBS:
#       1) Need to change the network name accordling to: 'project name + _default'
#           Ex: myproject_default
#       2) Need to change volumes path of dags and logs
#           Ex: my_absolute_dags_path:/home/engineer/dags
#       3) Need to change the image name accordling to: 'dag name + -worker'
#           Ex: my_dag_name-worker
#       4) Need to change the worker queue accordling to: 'image name + -queue'
#           Ex: my_dag_name-worker-queue

version: '3'
services:

  template-worker: #(3)
    build: .
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - FERNET_KEY
      - REMOTE_BASE_LOG_FOLDER
      - ENVIRONMENT=dev
      - MEMCACHED=True
      - MEMCACHE_HOST
      - MEMCACHE_PORT
    networks:
      - my-network
    command: airflow worker -q template-worker-queue #(4)
    restart: unless-stopped
    volumes:
      - ./../../dags:/home/engineer/dags:z #(2)
      - ./../../logs:/home/engineer/logs:z #(2)
    image: pra-ronauto-worker #(3)

networks:
  my-network:
      external:
          name: airzflow_template_default #(1)
